name: .NET Desktop Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: TextToSpeech.sln   # Replace with your solution name

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Specify your .NET version

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Build the solution
    - name: Build the application
      run: msbuild $env:Solution_Name /p:Configuration=Release

    # Upload build artifacts (the built executable files)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Executable Files
        path: |
          **\bin\Release\**\*.exe
          **\bin\Release\**\*.dll
